# Generated by Django 4.1 on 2023-07-16 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinemaapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cinema",
            name="img",
            field=models.ImageField(default="abcd", upload_to="gallary"),
            preserve_default=False,
        ),
    ]
